import assert from 'node:assert/strict';
import {existsSync} from 'node:fs';
import {resolve} from 'node:path';
import {pathToFileURL} from 'node:url';
const file=resolve('public/assets/demos/social-hub/accounts.mjs');
assert.ok(existsSync(file),'账号中心需要共享数据与持久化模块');
const {baseline,summary,filterAccounts,addAccount,reconnectAccount,removeAccount,updateOwner,loadState,saveState,STORAGE_KEY}=await import(pathToFileURL(file));
const initial=baseline();
assert.deepEqual(summary(initial.accounts),{total:10,connected:8,expired:2,platforms:5,owners:3,fans:128640});
assert.equal(filterAccounts(initial.accounts,{query:' 拾光日常 ',platform:'抖音',status:'expired'}).length,1);
assert.equal(filterAccounts(initial.accounts,{query:'拾光日常',platform:'小红书',status:'expired'}).length,0);
assert.equal(filterAccounts(initial.accounts,{}).length,10);
for(const input of [{name:' ',platform:'抖音',owner:'林晓'},{name:'测试',platform:'未知',owner:'林晓'},{name:'测试',platform:'抖音',owner:''}]) assert.throws(()=>addAccount(initial,input));
const added=addAccount(initial,{name:' 新账号 ',platform:'抖音',owner:' 林晓 '});
assert.equal(initial.accounts.length,10);assert.equal(added.accounts.length,11);
assert.equal(added.accounts.at(-1).name,'新账号');assert.equal(added.accounts.at(-1).fans,0);
assert.equal(new Set(added.accounts.map(a=>a.id)).size,11);
assert.throws(()=>addAccount(added,{name:'新账号',platform:'抖音',owner:'林晓'}),/已存在/);
const expired=initial.accounts.find(a=>a.status==='expired');
const connected=reconnectAccount(initial,expired.id);
assert.equal(summary(connected.accounts).connected,9);assert.equal(expired.status,'expired');
assert.deepEqual(reconnectAccount(connected,expired.id),connected);
assert.throws(()=>reconnectAccount(initial,'missing'));
const removed=removeAccount(added,added.accounts.at(-1).id);
assert.equal(removed.accounts.length,10);assert.deepEqual(summary(removed.accounts),summary(initial.accounts));
let value=null;const storage={getItem:()=>value,setItem:(key,v)=>{assert.equal(key,STORAGE_KEY);value=v;}};
assert.equal(saveState(added,storage),true);assert.deepEqual(loadState(storage).state,added);
value='{broken';assert.equal(loadState(storage).state.accounts.length,10);assert.ok(loadState(storage).warning);
value=JSON.stringify({version:1,accounts:[{id:'bad'}]});assert.equal(loadState(storage).state.accounts.length,10);
value=JSON.stringify({...initial,accounts:[initial.accounts[0],initial.accounts[0]]});assert.equal(loadState(storage).state.accounts.length,10);
assert.equal(saveState(initial,{setItem(){throw Error('blocked');}}),false);
assert.ok(loadState({getItem(){throw Error('blocked');}}).warning);
assert.equal(saveState(baseline(),storage),true);assert.equal(loadState(storage).state.accounts.length,10);
assert.equal(baseline().accounts.length,10);
console.log('通过：账号基线、组合筛选、字段及重复校验、不可变更新、重新连接、移除、持久化与损坏恢复。');

assert.equal(typeof updateOwner,'function','账号负责人应可修改');
const assigned=updateOwner(initial,initial.accounts[0].id,' 新负责人 ');
assert.equal(assigned.accounts[0].owner,'新负责人');assert.equal(summary(assigned.accounts).owners,4);assert.equal(initial.accounts[0].owner,'林晓');
assert.throws(()=>updateOwner(initial,initial.accounts[0].id,' '));
