import assert from 'node:assert/strict';
import {existsSync} from 'node:fs';
import {resolve} from 'node:path';
import {pathToFileURL} from 'node:url';
const path=resolve('public/assets/demos/social-hub/publishing.mjs');
assert.ok(existsSync(path),'需要可重试且保留账号快照的模拟发布任务');
const {emptyPublishing,createJob,executeJob,retryJob,cancelJob,removeAccountJobs,normalizePublishing,validateFiles}=await import(pathToFileURL(path));
const accounts=[1,2,3,4].map(n=>({id:`account-${n}`,name:`账号${n}`,platform:'抖音',owner:'林晓',status:n===4?'expired':'connected'}));
const draft={title:'标题',body:'正文\n保持内容'};const now=Date.now();
const initial={...emptyPublishing(),selectedIds:accounts.slice(0,3).map(a=>a.id),scenario:'partial'};
const make=(p=initial,opts={})=>createJob(p,accounts,draft,{id:'job-1',now,...opts});
assert.throws(()=>make({...initial,selectedIds:[]}));assert.throws(()=>make({...initial,selectedIds:['account-4']}));assert.throws(()=>createJob(initial,accounts,{title:' ',body:'正文'},{id:'job-1',now}));
let published=make();assert.deepEqual(published.jobs[0].results.map(r=>r.status),['success','success','failed']);assert.equal(published.jobs[0].results[0].interactions,0);assert.equal(initial.jobs.length,0);
assert.deepEqual(createJob(published,accounts,draft,{id:'job-1',now}),published);
let retried=retryJob(published,'job-1',accounts,now+1);assert.equal(retried.jobs[0].results.filter(r=>r.status==='success').length,3);assert.equal(retried.jobs[0].results.length,3);assert.equal(retried.jobs[0].results[0].attempts,1);assert.equal(retried.jobs[0].results[2].attempts,2);assert.deepEqual(retryJob(retried,'job-1',accounts,now+2),retried);
assert.throws(()=>make({...initial,mode:'scheduled',scheduledAt:now-1}));
let scheduled=make({...initial,mode:'scheduled',scheduledAt:now+1000});assert.ok(scheduled.jobs[0].results.every(r=>r.status==='pending'));
assert.throws(()=>executeJob(scheduled,'job-1',accounts,now));
assert.ok(normalizePublishing(scheduled).jobs[0].results.every(r=>r.status==='pending'),'重新加载不自动执行');
const cancelled=cancelJob(scheduled,'job-1');assert.ok(cancelled.jobs[0].results.every(r=>r.status==='cancelled'));assert.deepEqual(executeJob(cancelled,'job-1',accounts,now+2000),cancelled);
const executed=executeJob(scheduled,'job-1',accounts,now+2000);assert.deepEqual(executed.jobs[0].results.map(r=>r.status),['success','success','failed']);
const removed=removeAccountJobs(scheduled,'account-1');assert.equal(removed.jobs[0].results[0].status,'cancelled');assert.equal(removed.jobs[0].results[0].account.name,'账号1');
assert.equal(removeAccountJobs(published,'account-1').jobs[0].results[0].status,'success');
assert.throws(()=>retryJob(published,'job-1',accounts.filter(a=>a.id!=='account-3'),now));
assert.deepEqual(normalizePublishing({jobs:[{}]}),emptyPublishing());
assert.throws(()=>validateFiles([{type:'text/plain',size:1,name:'x.txt'}]));assert.throws(()=>validateFiles([{type:'image/png',size:21*1024*1024,name:'large.png'}]));
assert.equal(validateFiles([{type:'image/png',size:100,name:'demo.png'}]).length,1);
const {baseline,saveState,loadState,removeAccount,addAccount}=await import(pathToFileURL(resolve('public/assets/demos/social-hub/accounts.mjs')));
const state={...baseline(),publishing:scheduled};let raw;const storage={setItem:(_,v)=>raw=v,getItem:()=>raw};saveState(state,storage);assert.deepEqual(loadState(storage).state.publishing,scheduled);
assert.equal(removeAccount(state,'account-1').publishing.jobs[0].results[0].status,'cancelled');
const next=addAccount(removeAccount(state,'account-1'),{name:'新账号',owner:'林晓',platform:'抖音'});assert.notEqual(next.accounts.at(-1).id,'account-1');
assert.deepEqual(baseline().publishing,emptyPublishing());
console.log('通过：模拟发布、幂等重试、定时校验、取消、过期手动执行、账号快照、素材校验与持久化。');
