import assert from 'node:assert/strict';
import {existsSync} from 'node:fs';
import {resolve} from 'node:path';
import {pathToFileURL} from 'node:url';
const file=resolve('public/assets/demos/social-hub/content.mjs');
assert.ok(existsSync(file),'需要可编辑和跨模块传递的模拟创作数据');
const {emptyContent,generateDraft,transferDraft,normalizeContent}=await import(pathToFileURL(file));
const input={topic:'周末城市散步',platform:'小红书',style:'轻松治愈'};
assert.throws(()=>generateDraft({...input,topic:'  '},0),/主题/);
assert.throws(()=>generateDraft({...input,platform:'未知'},0));
assert.throws(()=>generateDraft({...input,style:'未知'},0));
const first=generateDraft(input,0),second=generateDraft(input,1);
assert.ok(first.body.includes(input.topic));assert.notEqual(first.body,second.body);
for(const platform of ['抖音','微信公众号','视频号','哔哩哔哩'])assert.notEqual(generateDraft({...input,platform},0).body,first.body);
for(const style of ['专业实用','活泼有趣'])assert.notEqual(generateDraft({...input,style},0).body,first.body);
const edited={title:'  手工标题 & < >  ',body:'第一行\n\n修改后的正文 🌿  '};
const content={...emptyContent(),draft:edited};
const moved=transferDraft(content);assert.deepEqual(moved.publish,edited);assert.notEqual(moved.publish,edited);assert.deepEqual(content.publish,emptyContent().publish);
assert.throws(()=>transferDraft({...content,draft:{title:' ',body:'正文'}}));
assert.deepEqual(normalizeContent(null),emptyContent());
assert.deepEqual(normalizeContent({...content,settings:input}),{...content,settings:input});
const {baseline,loadState,saveState}=await import(pathToFileURL(resolve('public/assets/demos/social-hub/accounts.mjs')));
let saved;const storage={getItem:()=>saved??null,setItem:(_,v)=>saved=v};
const state={...baseline(),content:{...moved,settings:input}};
saveState(state,storage);assert.deepEqual(loadState(storage).state.content,state.content);
const old=baseline();delete old.content;saved=JSON.stringify(old);assert.deepEqual(loadState(storage).state.content,emptyContent());
saved=JSON.stringify({...old,content:{draft:12}});assert.deepEqual(loadState(storage).state.content,emptyContent());
assert.deepEqual(baseline().content,emptyContent());
console.log('通过：主题校验、平台风格差异、生成变体、逐字传递、草稿持久化、旧数据兼容与重置。');
