import assert from 'node:assert/strict';import {existsSync} from 'node:fs';import {resolve} from 'node:path';import {pathToFileURL} from 'node:url';
const path=resolve('public/assets/demos/social-hub/analytics.mjs');assert.ok(existsSync(path),'看板需要基于记录的统一统计');
const {analytics}=await import(pathToFileURL(path));const {baseline}=await import(pathToFileURL(resolve('public/assets/demos/social-hub/accounts.mjs')));const {createJob,retryJob,cancelJob}=await import(pathToFileURL(resolve('public/assets/demos/social-hub/publishing.mjs')));
const now=Date.parse('2026-09-06T12:00:00+08:00'),state=baseline();const seven=analytics(state,{days:7,platform:'',now});assert.equal(seven.posts,48);assert.equal(seven.interactions,8926);assert.equal(seven.accounts,10);assert.equal(seven.fans,128640);assert.equal(seven.trend.reduce((s,d)=>s+d.interactions,0),seven.interactions);assert.equal(seven.distribution.reduce((s,d)=>s+d.interactions,0),seven.interactions);
assert.ok(analytics(state,{days:30,now}).posts>seven.posts);const red=analytics(state,{days:7,platform:'小红书',now});assert.equal(red.accounts,2);assert.ok(red.records.every(r=>r.account.platform==='小红书'));assert.equal(red.posts,red.records.length);
state.publishing=createJob({...state.publishing,selectedIds:state.accounts.slice(0,3).map(a=>a.id)},state.accounts,{title:'测试',body:'正文'},{id:'new',now});assert.equal(analytics(state,{days:7,now}).posts,50);state.publishing=retryJob(state.publishing,'new',state.accounts,now);const result=analytics(state,{days:7,now});assert.equal(result.posts,51);assert.equal(result.interactions,8926);assert.equal(result.newPosts,3);assert.ok(result.records.filter(r=>r.source==='task').every(r=>r.interactions===0));assert.equal(analytics({...state,publishing:retryJob(state.publishing,'new',state.accounts,now)},{days:7,now}).posts,51);
const later=Date.parse('2027-01-06T12:00:00+08:00');assert.equal(analytics(state,{days:7,now:later}).posts,48,'旧任务移出窗口，示例样本按当前日期对齐');
assert.equal(analytics(state,{days:7,platform:'不存在',now}).posts,0);assert.equal(analytics(state,{days:7,platform:'不存在',now}).interactions,0);
console.log('通过：7/30天与平台一致聚合、成功发布计数、重试去重、互动为0、时间窗口及空数据。');
