import {useEffect,useState} from 'react';
import {ArrowUpRight,ArrowRight,House,Moon,Sun,MessageCircle,ShieldCheck,Brain,SlidersHorizontal,Check} from 'lucide-react';
import './product.css';
const scenarios=[
 {name:'准备睡觉',icon:Moon,tag:'留一点光，把一天慢慢放下。',request:'准备睡觉了，帮我调整一下。',reply:'建议调暗床头灯、关闭窗帘，把卧室空调设为 26°C。',actions:['床头灯 · 亮度 15%','卧室空调 · 26°C','卧室窗帘 · 关闭'],note:'结合当前设备与已保存偏好，提出睡眠计划。没有偏好时，数值只是待确认的建议。'},
 {name:'回到家里',icon:House,tag:'让家，比你先进入状态。',request:'我回家了。',reply:'要打开客厅灯，给家里添一点声音吗？',actions:['客厅灯 · 开启','客厅音箱 · 音量 30%'],note:'通过模拟回家事件，体验 Agent 主动提出建议；同类事件 5 分钟内不会重复提醒。'},
 {name:'随手调整',icon:Sun,tag:'一句话，刚刚好的舒适。',request:'把卧室灯打开，亮度调到三成。',reply:'床头灯开启，亮度调至 30%。确认后为你调整。',actions:['床头灯 · 开启，亮度 30%'],note:'将自然语言转为具体设备参数。先核对设备，再等待确认，执行后呈现实际结果。'},
];
export function ProductPage(){
 const [selected,setSelected]=useState(0);const scene=scenarios[selected];
 useEffect(()=>{const previous=document.title;document.title='栖居 · 让家听懂你的生活';window.scrollTo(0,0);return()=>{document.title=previous;};},[]);
 const scroll=(id:string)=>document.getElementById(id)?.scrollIntoView({behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});
 return <main className="qp-page">
  <nav className="qp-nav" aria-label="产品介绍导航"><a className="qp-brand" href="#works"><span>栖</span>栖居 <small>HOME COMPANION</small></a><div><button onClick={()=>scroll('qp-scenes')}>使用场景</button><button onClick={()=>scroll('qp-principles')}>设计思路</button><a className="qp-link" href="#home-agent">体验 Demo <ArrowUpRight size={16}/></a></div></nav>
  <section className="qp-hero"><div className="qp-hero-copy"><p className="qp-eyebrow">AI HOME AGENT · 产品探索 / 01</p><h1>让家听懂<br/>你的<span>生活。</span></h1><p className="qp-lead">从一句“准备睡觉了”，<br/>到灯光、温度与窗帘的恰当配合。</p><p className="qp-intro">栖居是一位会理解需求、记住偏好、提出建议的 AI 家庭管家。让设备之间的协调，变成一次自然的对话。</p><a className="qp-primary" href="#home-agent">和栖居聊聊 <ArrowUpRight size={19}/></a><span className="qp-caption">可交互 Demo · 模拟家庭设备</span></div>
   <div className="qp-hero-stage"><span className="qp-orbit-label">YOUR SPACE, IN BALANCE</span><div className="qp-phone" aria-label="睡眠场景界面示意"><div className="qp-phone-top"><span>栖居</span><span><i/>家庭管家</span></div><p className="qp-phone-date">一个安静的夜晚 · 界面示意</p><div className="qp-chat-user">准备睡觉了。</div><div className="qp-chat-bot">把灯光调柔和一些，<br/>窗帘也为你合上。<br/><small>以下调整，等你确认。</small></div><div className="qp-mini-plan"><strong>今晚的舒适计划</strong><p><i className="blue"/>床头灯调暗至 15%</p><p><i/>空调设为 26°C</p><p><i className="red"/>关闭卧室窗帘</p><a href="#home-agent">进入 Demo 体验 <ArrowRight size={14}/></a></div><div className="qp-phone-input">告诉我，你想调整什么… <MessageCircle size={20}/></div></div><div className="qp-float-note"><ShieldCheck size={22}/><div>主动理解，确认后行动。<small>每一次调整，都由你决定。</small></div></div></div>
  </section>
  <div className="qp-facts"><div><b>自然语言</b><span>表达需求</span></div><div><b>6 台模拟设备</b><span>灯光 · 空调 · 窗帘等</span></div><div><b>24 小时</b><span>对话与上下文保留</span></div><div><b>确认后执行</b><span>决定权始终在你</span></div></div>
  <section className="qp-section qp-scenes" id="qp-scenes"><div className="qp-section-head"><p className="qp-eyebrow">01 / EVERYDAY MOMENTS</p><h2>日常的小事，<br/>值得被好好照顾。</h2><p>把分散的设备操作，放回真实的生活场景里。</p></div><div className="qp-tabs" role="tablist" aria-label="使用场景">{scenarios.map((s,i)=>{const Icon=s.icon;return <button key={s.name} role="tab" id={`qp-tab-${i}`} aria-selected={selected===i} aria-controls="qp-scenario-panel" onClick={()=>setSelected(i)}><Icon size={18}/>{s.name}</button>;})}</div><div className="qp-scene-panel" role="tabpanel" id="qp-scenario-panel" aria-labelledby={`qp-tab-${selected}`}><div><span className="qp-scene-number">0{selected+1}</span><h3>{scene.tag}</h3><p>{scene.note}</p><a href="#home-agent">在 Demo 中试一试 <ArrowUpRight size={17}/></a></div><div className="qp-scene-chat"><span className="qp-preview-label">场景示意 · 不会操作设备</span><p className="qp-chat-user">{scene.request}</p><div className="qp-chat-bot">{scene.reply}<ul>{scene.actions.map(a=><li key={a}><Check size={15}/>{a}</li>)}</ul></div></div></div></section>
  <section className="qp-process qp-section" id="qp-principles"><p className="qp-eyebrow">02 / FROM INTENT TO ACTION</p><h2>听懂一句话，<br/>还要把事情做好。</h2><p className="qp-process-lead">模型负责理解和规划，工具负责读取与执行。<br/>把一次对话，变成有依据、有确认、有结果的行动。</p><div className="qp-steps">{[['01','理解需求','识别设备、场景与目标；含糊时先询问。'],['02','查看状态','读取最新设备状态，参考已保存偏好。'],['03','提出计划','将建议变成可核对的具体调整，等待确认。'],['04','执行反馈','逐项执行，呈现变动；失败时明确说明。']].map(([n,title,copy])=><article key={n}><span>{n}</span><h3>{title}</h3><p>{copy}</p></article>)}</div></section>
  <section className="qp-section qp-boundaries"><div className="qp-section-head"><p className="qp-eyebrow">03 / DESIGNED WITH BOUNDARIES</p><h2>懂得记住，<br/>也懂得分寸。</h2></div><div className="qp-principles"><article><Brain size={25}/><h3>临时指令，不等于长期偏好</h3><p>对话与上下文保留 24 小时。明确要求记住并确认后，偏好才会保存；你可以随时修改或删除。</p></article><article><ShieldCheck size={25}/><h3>有主动性，也有决定权</h3><p>模拟回家、睡眠事件可以触发建议。设备调整需要确认，取消就不执行，重复事件也不会连续打扰。</p></article><article><SlidersHorizontal size={25}/><h3>如实反馈每一次变动</h3><p>开启、关闭、调参用不同信号灯表示。设备离线或部分执行失败时，直接说明结果，不将失败包装成成功。</p></article></div></section>
  <section className="qp-end"><span className="qp-eyebrow">MEET YOUR HOME COMPANION</span><h2>家的下一种交互，<br/>从一句话开始。</h2><a className="qp-primary" href="#home-agent">体验栖居 Demo <ArrowUpRight size={19}/></a><p>当前为产品演示：真实模型调用，模拟设备执行。<br/>未接入真实硬件、定位或后台定时任务；数据保存在当前浏览器。</p></section>
  <footer className="qp-footer"><span>栖居 · AI 家庭管家</span><span>产品设计与实现 · 耿乐</span><a href="#works">返回个人项目 <ArrowUpRight size={14}/></a></footer>
 </main>;
}
